services:
  - type: web
    name: turathi-api
    runtime: php
    plan: free
    buildCommand: composer install --no-dev --no-interaction --prefer-dist
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_DATABASE
        fromDatabase:
          name: turathi-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: turathi-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: turathi-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: turathi-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: turathi-db
          property: port
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: RECAPTCHA_SITE_KEY
        value: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - key: RECAPTCHA_SECRET_KEY
        value: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

databases:
  - name: turathi-db
    plan: free
    databaseName: turathi
